// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1ID5dRnVtGdCZAbPZ7XlLMLenDWIMzw',
    appId: '1:172447300039:web:3bdc06bf615caf446a81e2',
    messagingSenderId: '172447300039',
    projectId: 'looks-2db38',
    authDomain: 'looks-2db38.firebaseapp.com',
    databaseURL: 'https://looks-2db38-default-rtdb.firebaseio.com',
    storageBucket: 'looks-2db38.appspot.com',
    measurementId: 'G-ERYQ73MXHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGj3moHyUCs33d_AmDmT2Y7yU9iLrMxzQ',
    appId: '1:172447300039:android:21dc7ce20e9e914a6a81e2',
    messagingSenderId: '172447300039',
    projectId: 'looks-2db38',
    databaseURL: 'https://looks-2db38-default-rtdb.firebaseio.com',
    storageBucket: 'looks-2db38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp7D4u-KXZj11w5F08R9Bb-xOQvtZxz70',
    appId: '1:172447300039:ios:570506cbe4bd69786a81e2',
    messagingSenderId: '172447300039',
    projectId: 'looks-2db38',
    databaseURL: 'https://looks-2db38-default-rtdb.firebaseio.com',
    storageBucket: 'looks-2db38.appspot.com',
    androidClientId: '172447300039-3qjiebqr6s2gbs6ce2076nj0bgrta0hf.apps.googleusercontent.com',
    iosClientId: '172447300039-dc0mc0lccug1ktlfkhjh74u9l6vop5h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlGanadero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp7D4u-KXZj11w5F08R9Bb-xOQvtZxz70',
    appId: '1:172447300039:ios:570506cbe4bd69786a81e2',
    messagingSenderId: '172447300039',
    projectId: 'looks-2db38',
    databaseURL: 'https://looks-2db38-default-rtdb.firebaseio.com',
    storageBucket: 'looks-2db38.appspot.com',
    androidClientId: '172447300039-3qjiebqr6s2gbs6ce2076nj0bgrta0hf.apps.googleusercontent.com',
    iosClientId: '172447300039-dc0mc0lccug1ktlfkhjh74u9l6vop5h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.controlGanadero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ1ID5dRnVtGdCZAbPZ7XlLMLenDWIMzw',
    appId: '1:172447300039:web:988b3572d8458a826a81e2',
    messagingSenderId: '172447300039',
    projectId: 'looks-2db38',
    authDomain: 'looks-2db38.firebaseapp.com',
    databaseURL: 'https://looks-2db38-default-rtdb.firebaseio.com',
    storageBucket: 'looks-2db38.appspot.com',
    measurementId: 'G-Y6GQ7ZTPY2',
  );

}